/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as protectedIndexRouteImport } from './routes/(protected)/index'
import { Route as publicSigninRouteImport } from './routes/(public)/signin'
import { Route as protectedAccountRouteImport } from './routes/(protected)/account'
import { Route as protectedPatientsIndexRouteImport } from './routes/(protected)/patients/index'
import { Route as protectedPatientsRegisterRouteImport } from './routes/(protected)/patients/register'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedIndexRoute = protectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const publicSigninRoute = publicSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => publicRouteRoute,
} as any)
const protectedAccountRoute = protectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedPatientsIndexRoute = protectedPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedPatientsRegisterRoute =
  protectedPatientsRegisterRouteImport.update({
    id: '/patients/register',
    path: '/patients/register',
    getParentRoute: () => protectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/account': typeof protectedAccountRoute
  '/signin': typeof publicSigninRoute
  '/': typeof protectedIndexRoute
  '/patients/register': typeof protectedPatientsRegisterRoute
  '/patients/': typeof protectedPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/account': typeof protectedAccountRoute
  '/signin': typeof publicSigninRoute
  '/': typeof protectedIndexRoute
  '/patients/register': typeof protectedPatientsRegisterRoute
  '/patients': typeof protectedPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(protected)/account': typeof protectedAccountRoute
  '/(public)/signin': typeof publicSigninRoute
  '/(protected)/': typeof protectedIndexRoute
  '/(protected)/patients/register': typeof protectedPatientsRegisterRoute
  '/(protected)/patients/': typeof protectedPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/account' | '/signin' | '/' | '/patients/register' | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to: '/account' | '/signin' | '/' | '/patients/register' | '/patients'
  id:
    | '__root__'
    | '/(protected)'
    | '/(public)'
    | '/(protected)/account'
    | '/(public)/signin'
    | '/(protected)/'
    | '/(protected)/patients/register'
    | '/(protected)/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/': {
      id: '/(protected)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(public)/signin': {
      id: '/(public)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof publicSigninRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(protected)/account': {
      id: '/(protected)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof protectedAccountRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/patients/': {
      id: '/(protected)/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof protectedPatientsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/patients/register': {
      id: '/(protected)/patients/register'
      path: '/patients/register'
      fullPath: '/patients/register'
      preLoaderRoute: typeof protectedPatientsRegisterRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface protectedRouteRouteChildren {
  protectedAccountRoute: typeof protectedAccountRoute
  protectedIndexRoute: typeof protectedIndexRoute
  protectedPatientsRegisterRoute: typeof protectedPatientsRegisterRoute
  protectedPatientsIndexRoute: typeof protectedPatientsIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedAccountRoute: protectedAccountRoute,
  protectedIndexRoute: protectedIndexRoute,
  protectedPatientsRegisterRoute: protectedPatientsRegisterRoute,
  protectedPatientsIndexRoute: protectedPatientsIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicSigninRoute: typeof publicSigninRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicSigninRoute: publicSigninRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
